### ISSUE TITLE
GAN i carry

### ISSUE THREAD

**Issue by LilaQ** [Alex-Beng/PySmartCubeGenshin#1]
Hi there!

I'm trying to get the GAN i carry to work as well, but I can't figure out the decryption. Sadly I get assertion errors with your code too. Could you elaborate a bit on it, so maybe I can get it to work too?

Thanks a lot in advance!

**Comment by Alex-Beng** [comment]
could you provide the assert erro message that printed in the console? actually there are two different types of GAN cube using different decryption, which you can see it in [cstimer implement](https://github.com/cs0x7f/cstimer/blob/master/src/js/bluetooth.js#L467-L500). The cstimer will judge which one to use depending on the BLE‘s server and characteristic name. 
This project ONLY implement the v2 decryption, because i only have GAN i3 which is v2. I guess GAN i carry is using v1 decryption, and it will raise assertion error in [here](https://github.com/Alex-Beng/PySmartCubeGenshin/blob/master/src/gancube.py#L34).

**Comment by LilaQ** [comment]
Thanks for the quick reply! And thanks for the cstimer link, didn't even know that existed (I'm super new to cubing).

So, I'm getting issues here:
`mac = list(map(int, mac.split(':'), [16]*6))`

*ValueError: invalid literal for int() with base 16: '61B4D09C-CC58-2C69-3EF4-5862AB583D82'*
(not sure where I saw the Assertion Error first, I think I'm up too long at this point :D)

If I change it to `mac = list(map(int, mac.split(':'), [16]*6))` (as I assumed you were just splitting the uuid here) I'm getting index errors in `key[i]  = (key[i] + mac[5-i]) % 255`

Sadly I have no idea how the address of your i3 cube looks like, or I may have made some sense of it. 
Looking forward to your reply!

**Comment by Alex-Beng** [comment]
This line works to take BLE mac addr apart. And also the mac addr should not be this long. It looks like a BLE uuid rather than BLE mac addr, which should be the same format as network card mac like `12:34:56:78:9a:bc`  rather than `61B4D09C-CC58-2C69-3EF4-5862AB583D82`.

**Comment by LilaQ** [comment]
Weird, is the `address` field of the results of `BleakScanner.discover()` supposed to give out the MAC address? It only shows BLE uuid's for all the devices close to me.
(Mac address would of course make a lot more sense)

**Comment by LilaQ** [comment]
Okay, so, macos apparently needs a hacky workaround for bleak to show Mac address instead of uuids.

`devices = await BleakScanner.discover(return_adv=True, cb=dict(use_bdaddr=True))`

does the trick

**Comment by Alex-Beng** [comment]
LOL, it is the bleak bug actually

**Comment by Alex-Beng** [comment]
i just push a fix to master, it will help if you can test it . Thanks a lot.
